CREATE TABLE organizers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    moduleA BOOLEAN NOT NULL DEFAULT FALSE,
    moduleB BOOLEAN NOT NULL DEFAULT FALSE,
    moduleC BOOLEAN NOT NULL DEFAULT FALSE
);